# Generated by Django 4.1.7 on 2023-02-16 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='email',
            new_name='cnpj',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='telefone',
            new_name='numero',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='descricao',
        ),
    ]
