# Generated by Django 4.1.7 on 2023-02-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_empresa_cliente_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='empenho',
            field=models.FileField(default=1, upload_to='empenhos/'),
            preserve_default=False,
        ),
    ]
