# Generated by Django 4.1.7 on 2023-02-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_cliente_empenho'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
