# Generated by Django 4.1.7 on 2023-03-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_cliente_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='valor',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
