# Generated by Django 4.1.7 on 2023-05-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_cliente_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='n_nfe',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='nfe',
            field=models.FileField(default=0, upload_to='notas/'),
            preserve_default=False,
        ),
    ]
