# Generated by Django 4.1.7 on 2023-05-24 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0008_alter_cliente_empenho_alter_cliente_nfe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='n_nfe',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
