# Generated by Django 4.1.7 on 2023-05-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0009_alter_cliente_cnpj_alter_cliente_n_nfe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nfe',
            field=models.FileField(blank=True, default='0', max_length=500, upload_to='notas/'),
        ),
    ]
